const Data = [
    {
      id: 1,
      title: 'Chole Bhature',
      category: 'Breakfast',
      price: 180.00,
      img: "./images/Bhature.jpg",
      desc: `One of the north-India's most famous breakfast. You put one bite of our classic Chole Bhature and you get the taste of north-India `,
    },
    {
      id: 2,
      title: 'Butter Chicken',
      category: 'Lunch',
      price: 550.00,
      img: './images/butterChicken.jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'Godzilla Milkshake',
      category: 'Shakes',
      price: 220.00,
      img: './images/item-3.jpeg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'Omelet',
      category: 'Breakfast',
      price: 120.00,
      img: './images/Omelet.jpg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'Paneer Masala',
      category: 'Lunch',
      price: 320.00,
      img: './images/PaneerButter.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'Oreo Dream',
      category: 'Shakes',
      price: 175.00,
      img: './images/item-6.jpeg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'Ameican Classic',
      category: 'Lunch',
      price: 320.00,
      img: './images/item-8.jpeg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 8,
      title: 'Mango Shake',
      category: 'Shakes',
      price: 150.00,
      img: './images/Mangoshake.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 9,
      title: 'Samosa',
      category: 'Snacks',
      price: 50.00,
      img: './images/samosa.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 10,
      title: 'Pani Puri',
      category: 'Snacks',
      price: 80.00,
      img: './images/panipuri.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 11,
      title: 'Pav Bhaji',
      category: 'Snacks',
      price: 140.00,
      img: './images/pav-bhaji.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 12,
      title: 'Dosa',
      category: 'Breakfast',
      price: 110.00,
      img: './images/dosa.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 13,
      title: 'South Indian Deluxe',
      category: 'Lunch',
      price: 499,
      img: './images/SIbreakfast.jpeg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 14,
      title: 'Dal Fry',
      category: 'Lunch',
      price: 99.00,
      img: './images/Dalfry.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 15,
      title: 'Aloo Paramtha',
      category: 'Breakfast',
      price: 140.00,
      img: './images/AlooParantha.jpg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 16,
      title: 'Poori',
      category: 'Breakfast',
      price: 120.00,
      img: './images/Poori.jpg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    }
  ];
  export default Data;
  
